language: python
python:
# - "latest"
- '3.6'
# - '3.7-dev'
install:
- pip install coveralls
- pip install -r requirements.txt
script:
- coverage run -m unittest discover test/
after_success:
- coveralls
